"""Added new columns

Revision ID: ab775a3243b8
Revises: 
Create Date: 2024-01-30 22:45:02.642910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab775a3243b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('request_received_year', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('request_received_month', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('request_closed_year', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('request_closed_month', sa.String(), nullable=True))
        batch_op.alter_column('case_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason_grouped', sa.String(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('complaint_type')

    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_days', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('closed_on_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('case_active_grouped', sa.String(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('settings')

    with op.batch_alter_table('filter', schema=None) as batch_op:
        batch_op.alter_column('criteria',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('filter', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('criteria',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settings', sa.TEXT(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('case_active_grouped')
        batch_op.drop_column('closed_on_time')
        batch_op.drop_column('active_days')

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complaint_type', sa.TEXT(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('reason_grouped')

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('case_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('request_closed_month')
        batch_op.drop_column('request_closed_year')
        batch_op.drop_column('request_received_month')
        batch_op.drop_column('request_received_year')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
